name: Lint & Code Style

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

permissions:
  contents: read

jobs:
  lint:
    name: Code Formatting & Lint Checks
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff Linter
        run: |
          ruff check .

      - name: Run Ruff Formatter Check
        run: |
          ruff format --check .
